slug: privatebin
popularity: 36
tenant_installable: true
name: PrivateBin
tags: ["Developer tools"]
version: "2.0.6"
description: |
  Minimalist, open-source pastebin where the server has zero
  knowledge of pasted data. AES-256 client-side encryption. Single
  container, filesystem storage by default.
icon: icon.svg
upstream: https://github.com/PrivateBin/PrivateBin
documentation: https://github.com/PrivateBin/PrivateBin/wiki

image_channel: privatebin/nginx-fpm-alpine:2.0.6@sha256:13290e2f04bfd98cf8fc7e8d216fb76b2b2d12373d4923b859cd41c2d984fde8
update_mode: manual

resources:
  cpu: "0.5"
  memory: "128m"
  pids: 100

volumes:
  - name: data
    container_path: /srv/data

ports:
  - name: http
    container_port: 8080
    protocol: tcp
    default_enabled: true
    default_bind: loopback
    default_reverse_proxy: true
    health_path: /
